function l(b,a,d,c){b.i.Y(b.P,a,d,c)}function p(b,a,d,c){b.i.o?l(b,a,d,c):b.i.pb()._OnMessageFromDOM({type:"event",component:b.P,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.h(b.P,a,d)}function r(b,a){for(const [d,c]of a)q(b,d,c)}window.X=class{constructor(b,a){this.i=b;this.P=a}Da(){}};window.Xb=class{constructor(){}};"use strict";function aa(b,a){q(b,"get-element",d=>{const c=t(b,d.elementId);return a(c,d)})}
function t(b,a){b=b.ca.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Pa}
window.Wb=class extends self.X{constructor(b,a){super(b,a);this.ca=new Map;this.qa=!0;r(this,[["create",()=>{throw Error("required override");}],["destroy",d=>{d=d.elementId;const c=t(this,d);this.qa&&c.parentElement.removeChild(c);this.ca.delete(d)}],["set-visible",d=>{if(this.qa){var c=this.ca.get(d.elementId),e=c.Pa;c.Ta?e.style.display=d.isVisible?"":"none":c.Fb=!!d.isVisible}}],["update-position",d=>{if(this.qa){var c=this.ca.get(d.elementId),e=c.Pa;e.style.left=d.left+"px";e.style.top=d.top+
"px";e.style.width=d.width+"px";e.style.height=d.height+"px";d=d.fontSize;null!==d&&(e.style.fontSize=d+"em");c.Ta||(c.Ta=!0,c.Fb&&(e.style.display=""))}}],["update-state",d=>{t(this,d.elementId);throw Error("required override");}],["focus",d=>{const c=t(this,d.elementId);d.focus?c.focus():c.blur()}],["set-css-style",d=>{const c=t(this,d.elementId),e=d.prop;d=d.val;e.startsWith("--")?c.style.setProperty(e,d):c.style[e]=d}],["set-attribute",d=>{t(this,d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",
d=>{t(this,d.elementId).removeAttribute(d.name)}]]);aa(this,d=>d)}};"use strict";const u=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),ba=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let w=0;
function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Mb?new Promise(d=>{const c="c3_resolve_"+w;++w;self[c]=d;a.textContent=b.Qb+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}let y=!1,z=!1;function ca(){if(!y){try{new Worker("blob://",{get type(){z=!0}})}catch(b){}y=!0}return z}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(b){b=await B(b);return(new TextDecoder("utf-8")).decode(b)}
function B(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let fa=0;const ha=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ha.push(b)};const ia=new Set(["cordova","playable-ad","instant-games"]);let ja=!1;
window.Z=class b{constructor(a){this.o=a.Sb;this.T=null;this.m="";this.H=a.Pb;this.W={};this.wa=this.J=null;this.ba=[];this.j=this.D=null;this.Ua=!1;this.R=null;this.G=-1;this.Ib=()=>this.xb();this.za=[];this.Ba=null;this.Xa=[];this.g=a.Ya;this.ua="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ca()||(this.o=!1);this.o&&ba&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(v){const d=
/Chrome\/(\d+)/i.exec(navigator.userAgent);d&&90<=parseInt(d[1],10)||(this.o=!1)}else this.o=!1;this.M()?self.chrome.webview.addEventListener("message",d=>this.Ka(d.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=d=>this.Ka(d));this.da=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",d=>this.tb(d));this.h("runtime","create-job-worker",()=>this.ub());this.h("runtime","send-wrapper-extension-message",d=>this.Ab(d));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ia(a)):this.Ia(a)}cb(){return u&&"cordova"===this.g}la(){const a=navigator.userAgent;return u&&ia.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ab(){return v}Fa(){return v&&ia.has(this.g)}M(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Ia(a){"macos-wkwebview"===this.g?this.N({type:"ready"}):this.M()&&(this.Cb(),this.Xa=(await this.sb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.da={};await this.lb();for(let c=0,e=a.K.length;c<e;++c){var d=a.K[c];this.da.hasOwnProperty(d)?a.K[c]={Mb:!0,Qb:this.da[d]}:this.A.hasOwnProperty(d)&&(a.K[c]=URL.createObjectURL(this.A[d]))}a.ha=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let c=
0;this.hb(()=>{c++;document.body.style.opacity=0===c%2?"1":"0.999"})}a.Ob?this.m=a.Ob:(d=location.origin,this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.Ub&&(this.W=a.Ub);d=new MessageChannel;this.T=d.port1;this.T.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.wb(c));this.R=new self.eb(this);await ka(this.R);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.o?await this.rb(a,d.port2):await this.qb(a,d.port2)}na(a){a=this.W.hasOwnProperty(a)?this.W[a]:a.endsWith("/workermain.js")&&this.W.hasOwnProperty("workermain.js")?this.W["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ka(a,
d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.g&&this.ua)return a=await this.ja(c.Lb?a:this.H+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ha(a){var d=
this.m,c=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.L(),k=a.$b,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,ua=window.cr_previewProjectFiles,va=window.cr_swClientId||"";a=a.Ya;var wa=(new URLSearchParams(self.location.search)).has("debug"),I=this.R;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:ua,swClientId:va,
exportType:a,isDebug:wa,ife:!!self.Zb,jobScheduler:{inputPort:I.ta,outputPort:I.ya,maxNumWorkers:I.Gb},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.H+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.H+"opus.wasm.wasm",isFileProtocol:this.ua,isiOSCordova:this.cb(),isiOSWebView:this.la(),isWebView2Wrapper:this.M(),wrapperComponentIds:this.Xa,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rb(a,d){const c=this.na(a.Tb);"preview"===this.g?
(this.J=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=n=>{this.J.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():k()};this.J.addEventListener("message",m);this.J.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.J=await this.ka(c,this.m,{type:"module",name:"Runtime",Lb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ha||[],g=a.K;f=await Promise.all(f.map(h=>this.F(h)));g=await Promise.all(g.map(h=>this.F(h)));if("cordova"===this.g)for(let h=0,k=a.ga.length;h<k;++h){const m=a.ga[h],n=m[0];if(n===a.Ca||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.F(n)}this.J.postMessage(Object.assign(this.Ha(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.ga,mainProjectScript:a.Ca,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...la(this.R)]);this.ba=E.map(h=>new h(this));this.Ga();ma(this.D);self.c3_callFunction=(h,k)=>{var m=this.D;return m.i.fb(m.P,{name:h,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.Y("runtime","go-to-last-error-script"))}async qb(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.ba=E.map(g=>new g(this));this.Ga();var c=a.K.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ha)){var e=[...a.ha].map(g=>g instanceof Blob?URL.createObjectURL(g):g);c.unshift(...e)}c=await Promise.all(c.map(g=>this.F(g)));await Promise.all(c.map(g=>x(g)));c=self.C3_ProjectScriptsStatus;e=a.Ca;const f=a.ga;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.F(h),await x(h),"preview"!==this.g||c[g]||this.La(g,"main script did not run to completion")}catch(k){this.La(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.F(h),await x(h);"preview"===this.g&&"object"!==typeof self.Vb.Yb?(this.aa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ha(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:ha}),ma(this.D),
this.Ja(),this.wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.wa,a))}La(a,d){this.aa();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ja(){this.aa()}aa(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async ub(){const a=await na(this.R);return{outputPort:a,
transferables:[a]}}pb(){if(this.o)throw Error("not available in worker mode");return this.wa}Y(a,d,c,e){this.T.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},void 0)}fb(a,d){const c=fa++,e=new Promise((f,g)=>{G.set(c,{resolve:f,reject:g})});this.T.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.vb(a);if("result"===
d)this.yb(a);else if("runtime-ready"===d)this.zb();else if("alert-error"===d)this.aa(),alert(a.message);else if("creating-runtime"===d)this.Ja();else throw Error(`unknown message '${d}'`);}vb(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=F.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.$(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.$(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,
h);this.$(f,!1,""+h)}):this.$(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}$(a,d,c){let e;c&&c.transferables&&(e=c.transferables);this.T.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}yb(a){const d=a.responseId,c=a.isOk;a=a.result;const e=G.get(d);c?e.resolve(a):e.reject(a);G.delete(d)}h(a,d,c){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);
e.set(d,c)}static ia(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ga(){for(const a of this.ba)if("runtime"===a.P){this.D=a;return}throw Error("cannot find runtime DOM handler");}wb(a){this.Y("debugger","message",a)}zb(){for(const a of this.ba)a.Da()}static L(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ja)}static Ma(a){ja=!!a}hb(a){this.za.push(a);this.pa()}pa(){-1===this.G&&this.za.length&&(this.G=requestAnimationFrame(this.Ib))}jb(){-1!==
this.G&&(cancelAnimationFrame(this.G),this.G=-1)}xb(){this.G=-1;for(const a of this.za)a();this.pa()}oa(){this.D.oa()}gb(){this.Ua=!0}$a(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}bb(a){return!this.$a(a)}async F(a){return"cordova"===this.g&&(a.startsWith("file:")||this.ua&&this.bb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ja(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async tb(a){const d=a.filename;
switch(a.as){case "text":return await this.Za(d);case "buffer":return await this.ja(d);default:throw Error("unsupported type");}}Ea(a){const d=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async Za(a){a=await this.Ea(a);return await ea(a)}ma(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.mb(a.filename,a.Rb,a.Kb)}}ja(a){return new Promise((d,c)=>{C.push({filename:a,Rb:e=>{D--;this.ma();d(e)},Kb:e=>{D--;this.ma();
c(e)}});this.ma()})}async mb(a,d,c){try{const e=await this.Ea(a),f=await B(e);d(f)}catch(e){c(e)}}Ka(a){if("entered-fullscreen"===a)b.Ma(!0),H(this.D);else if("exited-fullscreen"===a)b.Ma(!1),H(this.D);else if("object"===typeof a){const d=a.type;"wrapper-init-response"===d?(this.Ba(a),this.Ba=null):"extension-message"===d?this.Y("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ab(a){this.N({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}N(a){this.M()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Cb(){window.moveTo=(a,d)=>{this.N({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(d)})};window.resizeTo=(a,d)=>{this.N({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(d)})}}sb(){return this.M()?new Promise(a=>
{this.Ba=a;this.N({type:"wrapper-init"})}):Promise.resolve()}async lb(){const a=[];for(const [d,c]of Object.entries(this.A))a.push(this.kb(d,c));await Promise.all(a)}async kb(a,d){if("object"===typeof d)this.A[a]=new Blob([d.str],{type:d.type}),this.da[a]=d.str;else{let c=await this.ob(d);c||(c=this.nb(d));this.A[a]=c}}async ob(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}nb(a){a=this.Bb(a);return this.ib(a.data,a.Nb)}Bb(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Nb:a,data:c}}ib(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=
3;c--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:d})}};"use strict";const J=self.Z;function oa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const pa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},qa={dispatchUserScriptEvent:!0},L={dispatchRuntimeEvent:!0};
function ra(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function sa(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function M(b){b=URL.createObjectURL(b);try{return await sa(b)}finally{URL.revokeObjectURL(b)}}
function ta(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function xa(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await M(b);var c=await ta(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await M(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await M(b)}
function N(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const ya=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);function O(b){b.target.tagName&&za.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Aa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await M(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await xa(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let P=!1;document.addEventListener("pause",()=>P=!0);document.addEventListener("resume",()=>P=!1);function ma(b){b.Ra=!0;b.va=b.i.v();b.S=b.i.u()}function H(b){if(!b.l){var a=J.L();a&&"any"!==b.Aa&&Ba(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Ca(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}function Fa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ga(b){self.setTimeout(()=>{b.Qa=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>Q(b,!0)),document.addEventListener("resume",()=>Q(b,!1))):document.addEventListener("visibilitychange",()=>Q(b,"hidden"===document.visibilityState));b.ea=!("hidden"!==document.visibilityState&&!P);return{isSuspended:b.ea}}
function Ha(b){b.Oa||(b.Oa=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ia(b){b.Na||(b.Na=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ja(b){await ra(b.url)}
function Ka(b,a){b.Sa=a.message;-1===b.sa&&(b.sa=setTimeout(()=>{b.sa=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Sa)},250))}function R(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:J.L(),innerWidth:b.v(),innerHeight:b.u()})}function Q(b,a){b.ea!==a&&((b.ea=a)?b.i.jb():b.i.pa(),l(b,"visibilitychange",{hidden:a}))}
function La(b,a,d){"Backspace"===d.key&&O(d);if(!b.l){var c=pa.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},K)}}function S(b,a,d,c){b.l||oa(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}
function T(b){window!==window.top&&window.focus();Ma(b.target)&&document.activeElement&&!Ma(document.activeElement)&&document.activeElement.blur()}
function U(b,a,d){if(!b.l){var c=0;"mouse"===d.pointerType&&(c=b.U);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},K);"mouse"===d.pointerType&&(c="mousemove",
"pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),S(b,c,d,qa),b.U=d.buttons)}}
function V(b,a,d){if(!b.l&&!oa(d)){var c=b.U;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},K);b.U=d.buttons;S(b,d.type,d,qa)}}
function W(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
K)}}function Y(b,a,d){document.body.style.transform="";b.s=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Na(b,a,d,c){const e=b.v(),f=b.u();b.I=-1;e!=a||f!=d?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.L()}):10>c&&Oa(b,e,f,c+1)}
function Oa(b,a,d,c){-1!==b.I&&clearTimeout(b.I);b.I=setTimeout(()=>Na(b,a,d,c),48)}
function Ba(b){b=b.Aa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ma(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.ia(class extends self.X{constructor(b){super(b,"runtime");this.Va=!0;this.Ra=!1;this.I=-1;this.Aa="any";this.ea=this.Na=this.Oa=!1;this.fa=document.createElement("div");this.fa.className="c3-screen-reader-text";this.fa.setAttribute("aria-live","polite");document.body.appendChild(this.fa);this.C=null;this.l=!1;this.Sa="";this.sa=-1;this.Qa=!1;this.va=b.v();this.S=b.u();this.s=this.V=0;b.h("canvas","update-size",c=>{var e=this.i;e.Ua||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+
"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",c.displayScale),this.Va&&(e.style.display="",this.Va=!1))});b.h("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",c=>Ca(c));b.h("runtime","raster-svg-image",c=>Da(c));b.h("runtime","get-svg-image-size",
c=>Ea(c));b.h("runtime","set-target-orientation",c=>{this.Aa=c.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",c=>Fa(c));b.h("runtime","go-to-script",c=>Fa(c));b.h("runtime","before-start-ticking",()=>Ga(this));b.h("runtime","debug-highlight",c=>{if(c.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=c.left-
1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.C&&(this.C.style.display="none")});b.h("runtime","enable-device-orientation",()=>Ha(this));b.h("runtime","enable-device-motion",()=>Ia(this));b.h("runtime","add-stylesheet",c=>Ja(c));b.h("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",c=>{alert(c.message)});b.h("runtime",
"screen-reader-text",c=>{var e=c.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+c.id,e.textContent=c.text,this.fa.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+c.id))?e.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===e?(e=document.getElementById("c3-sr-"+c.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.gb()});b.h("runtime","export-to-video-progress",c=>Ka(this,c));b.h("runtime","exported-to-video",c=>{window.Jb({type:"exported-video",
arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.h("runtime","exported-to-image-sequence",c=>{window.Jb({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||N(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);d.addEventListener("selectstart",O);d.addEventListener("gesturehold",
O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),d.addEventListener("pointerdown",O)):d.addEventListener("touchstart",O);this.U=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Ra){var c=this.v();var e=this.u();if(this.i.Fa()){if(this.Qa){if(this.va===
c&&e<this.S){this.V=this.S-e;Y(this,this.S,this.V);c=void 0;break a}0<this.V&&(this.V=0,Y(this,e,this.V))}this.va=c;this.S=e}l(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.L()});this.i.la()&&(-1!==this.I&&clearTimeout(this.I),Na(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>H(this));window.addEventListener("fullscreenerror",
c=>R(this,c));window.addEventListener("webkitfullscreenerror",c=>R(this,c));window.addEventListener("mozfullscreenerror",c=>R(this,c));if(b.la())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):N(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});this.xa=new Set;this.Hb=new WeakSet;this.Eb=!1}Da(){window.addEventListener("focus",()=>{l(this,"window-focus",null,L)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=!1}l(this,"window-blur",{parentHasFocus:a},L);this.U=0});window.addEventListener("focusin",a=>{a=a.target;(ya.has(a.tagName.toLowerCase())||N(a))&&
l(this,"keyboard-blur",null,L)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{T(a);U(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",
a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=()=>this.oa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.ab()&&!this.i.Fa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}oa(){var b=[...this.xa];this.xa.clear();if(!this.Eb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Hb.has(a)||this.xa.add(a)})}});"use strict";
async function ka(b){if(b.Db)throw Error("already initialised");b.Db=!0;var a=b.B.na(("playable-ad"===b.B.g?b.B.H:"")+"dispatchworker.js");b.ra=await b.B.ka(a,b.O,{name:"DispatchWorker"});a=new MessageChannel;b.ta=a.port1;b.ra.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ya=await na(b)}function la(b){return[b.ta,b.ya]}
async function na(b){const a=b.Wa.length;var d=b.B.na(("playable-ad"===b.B.g?b.B.H:"")+"jobworker.js");d=await b.B.ka(d,b.O,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.ra.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Wa.push(d);return e.port1}
self.eb=class{constructor(b){this.B=b;this.O=b.m;this.O="preview"===b.g?this.O+"workers/":this.O+b.H;this.Gb=Math.min(navigator.hardwareConcurrency||2,16);this.ra=null;this.Wa=[];this.ya=this.ta=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Z({Sb:!0,Tb:"workermain.js",K:["scripts/c3runtime.js"],ga:[],Ca:"",Pb:"scripts/",ha:[],Ya:"html5"}));"use strict";
async function Pa(b,a){a=a.type;let d=!0;0===a?d=await Qa():1===a&&(d=await Ra());l(b,"permission-result",{type:a,result:d})}async function Qa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ra(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Z.ia(class extends self.X{constructor(b){super(b,"touch");q(this,"request-permission",a=>Pa(this,a))}});"use strict";
self.Z.ia(class extends self.X{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
